### PR TITLE
Refactor- separate flag setting from main.go to flag.go

### PR DESCRIPTION
**Pull request by Iovesophy**

### CODE REVIEW

**Comment by Iovesophy** [comment]
Tried operation check ↓

```bash
go build main.go flag.go utils.go yubikey.go decrypt.go encrypt.go 
echo "hoge" > hoge.txt
./main -setup
./main -setup -reset
./main -encrypt -filename hoge.txt
./main -decrypt -filename hoge.txt_encrypted.bin
```

※ My YubiKey type is YubiKey 5C

**Comment by kumo-rn5s** [comment]
Actually, I'm thinking about what the main.go process should be in a package.
Main.go with flags can be implemented as a cli interface, or as part of a package. What do you think?

**Comment by Iovesophy** [comment]
Actually , This is not separate package , because main.go and flag.go in same package of main

If you need separate package , you should make dir and declare package <name>

**Comment by Iovesophy** [comment]
> Main.go with flags can be implemented as a cli interface

I'm agree , 
so this is not need separate file , but I think you should separate function for flag setting phase in main()

for example 

```Go
package main

import (
	"flag"
)

type flagVal struct {
	sample *int // defalut = 5
}

func (f *flagVal) getFlag() int {
	f.sample = flag.Int("n", 5, "defines num")
	flag.Parse()
	return *f.sample
}

// main
func main() {
	f := flagVal{}
        sampleFlagValue := f.getFlag()
}
```

**Comment by Iovesophy** [comment]
Done

**Pull request closed without merging**
